name: Docker build
on: [push, pull_request]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build -t samplepy ./bot
    #  - name: Run tests inside the container
    #   run: 
    #   тут может добавиться сборка докера с тестами и их запуск